### ISSUE TITLE
IDEA: It would be better to have a shortcut on context menu

### ISSUE THREAD

**Issue by oyavri** [brkydnc/tt#3]
It would be a better experience if we could disable the popup button on selecting text and instead of it, putting a shortcut to context menu.

**Comment by brkydnc** [comment]
57ea0ca9167f3fe7d8d0b3faefab0615fd243c2c adds context menu, 9abf69f6775851e5089ae322fa36a3b2417a0f74 implements support to disable the panel and the context menu.
